name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs_deploy.yml"
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: yarn
          cache-dependency-path: docs/yarn.lock
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        working-directory: docs
        run: yarn install --frozen-lockfile
      - name: Build website
        working-directory: docs
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
